import { CatalogItem, CategoryItem } from "../types/types";

const CAT_1_SUBCAT_7: CatalogItem[] = [
  {
    id: 85,
    name: "Фуксия  Blue Angel",
    description:
      "Блю Ангел крупноцветковая фуксия, которая идеально подходит для выращивания в подвесных корзинках. Фиолетово-голубой цвет в сочетании с ярко-белой чашечкой выглядит очень привлекательно. Этот сорт является одной из групп «Гигант», и все разновидности гигантских фуксий имеют длительный период цветения.",
    price: 100,
    vendorCode: 1,
    image: "85",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },
  {
    id: 86,
    name: "Фуксия Bella Rosella",
    description:
      "Сильнорослая, самоветвящаяся фуксия с очень крупными махровыми цветами. Длительное и обильное цветение. Полуампельный сорт. Цветы крупные, чашелистики белые с розовым напылением, юбочка темно розовая махровая.",
    price: 100,
    vendorCode: 2,
    image: "86",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },
  {
    id: 87,
    name: "Фуксия Bicentennial",
    description:
      "Ампельный сорт крупноцветковый, цветы окрашены в оранжевый цвет с различными оттенками красного цвета. Белые трубки пыльников создают еще более яркий контраст. Ветви длинные гибкие, очень устойчивые к сильному ветру и образуют пышный ниспадающий куст",
    price: 100,
    vendorCode: 3,
    image: "87",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },

  {
    id: 88,
    name: "Фуксия Blaze Away",
    description:
      "Ампельная, цветы среднего размера. Бутоны светло-розовые округлые с острым зеленоватым кончиком. Юбочка образована лепестками разной длины – более короткими по краю и длинными по центру. Светло-розовые чашелистики. Светло-розово-персиковая туба.",
    price: 100,
    vendorCode: 4,
    image: "88",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },

  {
    id: 89,
    name: "Фуксия Blue Mirage",
    description:
      "Ампельная форма, самоветвящаяся фуксия с очень ранним, обильным, продолжительным цветением. Цветы крупные махровые. Бутоны удлинённые. Чашелистики белые с зеленоватыми кончиками. Юбочка фиолетовая с белыми мазками.",
    price: 100,
    vendorCode: 5,
    image: "89",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },
  {
    id: 90,
    name: "Фуксия El Camino",
    description:
      "Удивительные цветы этих амельных фуксий достигают 8 см в диаметре. Растения быстро растут.Округлые бутоны. Цветы махровые очень крупные с большими центральными лепестками и меньшими внешними.Чашелистики красно-розовые, юбочка белая, испещрённая красными широкими мазками и прожилками.",
    price: 100,
    vendorCode: 6,
    image: "90",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },

  {
    id: 91,
    name: "Фуксия General",
    description:
      "Обильноцветущая фуксия, быстро формирует компактную, аккуратную крону. Цветы махровые мелкие. Чашелистики ярко-розовые. Юбочка синяя, со временем переходящая в насыщенно-фиолетовый цвет.",
    price: 100,
    vendorCode: 7,
    image: "91",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },

  {
    id: 92,
    name: "Фуксия Hang Dollar Princess",
    description:
      "Ампельная, махровая, цветение раннее. Цветок: махровый крупный, чашелистики красные, а юбочка ярко фиолетовая Время цветения: май-октябрь.",
    price: 100,
    vendorCode: 8,
    image: "92",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },
  {
    id: 93,
    name: "Фуксия Millenium",
    description:
      "Прекрасный полуампельный сорт с крупными махровыми цветками темно-фиолетового, почти черного, цвета. Этот сорт фуксии характеризуется сильным ростом и поздним сроком цветения.",
    price: 100,
    vendorCode: 9,
    image: "93",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },

  {
    id: 94,
    name: "Фуксия  Madame Cornelissen",
    description:
      "Полукустарник высотой до 50-100 см, с темной листвой и с крупными простыми цветками, на длинных цветоножках. Особое изящество цветкам придают окрашенные, с загнутыми вверх краями красные чашечки .",
    price: 100,
    vendorCode: 10,
    image: "94",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },

  {
    id: 95,
    name: "Фуксия Natalie",
    description:
      "Обильно цветущий сорт с махровыми крупными цветками. Подходит для выращивания как в подвесных кашпо, так и на штамбе. Бутоны продолговатые и крупные. Чашелистики палево-розовые. Юбочка розовая.",
    price: 100,
    vendorCode: 11,
    image: "95",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },
  {
    id: 96,
    name: "Фуксия Multa",
    description:
      "Сорт с отличным ветвлением. Сильный рост, пышные и аккуратные шапки. Цветки мелкие, немахровые. Средний срок цветения.",
    price: 100,
    vendorCode: 12,
    image: "96",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },

  {
    id: 97,
    name: "Фуксия  Magellanica Riccartonii",
    description:
      "Сильнорослая, позднего срока цветения Цветы: простые, ярко-красные с фиолетовой серединой. ",
    price: 100,
    vendorCode: 13,
    image: "97",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },

  {
    id: 98,
    name: "Фуксия Claudia",
    description: "Полуампельная с розовыми махровыми цветами среднего размера.",
    price: 100,
    vendorCode: 14,
    image: "98",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },
  {
    id: 99,
    name: "Фуксия Allison Patricia",
    description:
      "Компактный вид Фуксии. Эта фуксия особенно рекомендуется для выращивания в маленьких горшках. Полумахровая трубка красная. Чашелистики бледно-розово-красные с зелеными кончиками. Мелкие цветы.",
    price: 100,
    vendorCode: 15,
    image: "99",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },

  {
    id: 100,
    name: "Фуксия Gillian Anthea",
    description:
      "Крупные махровые цветы. Чашелистики насыщенно-розовые, почти красные. Юбочка светло-синяя с розовыми мазками. Побеги быстро одревесневают. Возможно выращивание штамбового деревца. ",
    price: 100,
    vendorCode: 16,
    image: "100",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },

  {
    id: 101,
    name: "Фуксия Beacone Rose",
    description:
      " Полуампельная форма. Цветение обильное. Цветки некрупные простые, розовые.",
    price: 100,
    vendorCode: 17,
    image: "101",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },
  {
    id: 102,
    name: "Фуксия Marinka",
    description:
      "Фуксия ампельная, обильноцветущая. Цветы простые, плотные, насыщенно-красно-малиновые.",
    price: 100,
    vendorCode: 18,
    image: "102",
    categoryId: 1,
    subCategoryId: 7,
    isAvailable: false,
  },
];

const CAT_1_SUBCAT_8: CatalogItem[] = [
  {
    id: 139,
    name: "Георгины XXL Tabasco",
    description: "",
    price: 100,
    vendorCode: 15,
    image: "139",
    categoryId: 1,
    subCategoryId: 8,
    isAvailable: true,
  },
  {
    id: 140,
    name: "Георгины XXL Veracruz",
    description: "",
    price: 100,
    vendorCode: 11,
    image: "140",
    categoryId: 1,
    subCategoryId: 8,
    isAvailable: true,
  },
  {
    id: 141,
    name: "Георгины XXL Berry Blast",
    description: "",
    price: 100,
    vendorCode: 14,
    image: "141",
    categoryId: 1,
    subCategoryId: 8,
    isAvailable: true,
  },

  {
    id: 142,
    name: "Георгины Labella Grande Red",
    description: "",
    price: 100,
    vendorCode: 8,
    image: "142",
    categoryId: 1,
    subCategoryId: 8,
    isAvailable: true,
  },

  {
    id: 143,
    name: "Георгины Labella Maggiore Fire",
    description: "",
    price: 100,
    vendorCode: 6,
    image: "143",
    categoryId: 1,
    subCategoryId: 8,
    isAvailable: true,
  },
  {
    id: 144,
    name: "Георгины Labella Piccolo Yellow",
    description: "",
    price: 100,
    vendorCode: 10,
    image: "144",
    categoryId: 1,
    subCategoryId: 8,
    isAvailable: true,
  },

  {
    id: 145,
    name: "Георгины Dalina Maxi Cancun",
    description: "",
    price: 100,
    vendorCode: 9,
    image: "145",
    categoryId: 1,
    subCategoryId: 8,
    isAvailable: true,
  },

  {
    id: 146,
    name: "Георгины Dalina Maxi Cozumel",
    description: "",
    price: 100,
    vendorCode: 12,
    image: "146",
    categoryId: 1,
    subCategoryId: 8,
    isAvailable: true,
  },

  {
    id: 147,
    name: "Георгины Dalina Mini Cruzilia",
    description: "",
    price: 100,
    vendorCode: 13,
    image: "147",
    categoryId: 1,
    subCategoryId: 8,
    isAvailable: true,
  },
  {
    id: 148,
    name: "Георгины Hypnotica White",
    description: "",
    price: 100,
    vendorCode: 16,
    image: "148",
    categoryId: 1,
    subCategoryId: 8,
    isAvailable: true,
  },
  {
    id: 149,
    name: "Георгины Labella Maggiore Purple",
    description: "",
    price: 100,
    vendorCode: 7,
    image: "149",
    categoryId: 1,
    subCategoryId: 8,
    isAvailable: true,
  },
];

const CAT_1_SUBCAT_9: CatalogItem[] = [
  {
    id: 103,
    name: "Бегония Haylei Soft Yellow",
    description: "",
    price: 200,
    vendorCode: 1,
    image: "103",
    categoryId: 1,
    subCategoryId: 9,
    isAvailable: false,
  },
  {
    id: 104,
    name: "Бегония элатиор Reina XL",
    description: "",
    price: 200,
    vendorCode: 2,
    image: "104",
    categoryId: 1,
    subCategoryId: 9,
    isAvailable: false,
  },
  {
    id: 105,
    name: "Бегония Reina Amber",
    description: "",
    price: 200,
    vendorCode: 3,
    image: "105",
    categoryId: 1,
    subCategoryId: 9,
    isAvailable: false,
  },

  {
    id: 106,
    name: "Бегония элатиор Rolinde",
    description: "",
    price: 200,
    vendorCode: 4,
    image: "106",
    categoryId: 1,
    subCategoryId: 9,
    isAvailable: false,
  },

  {
    id: 107,
    name: "Бегония элатиор Riley",
    description: "",
    price: 200,
    vendorCode: 5,
    image: "107",
    categoryId: 1,
    subCategoryId: 9,
    isAvailable: false,
  },
  {
    id: 108,
    name: "Бегония Romance",
    description: "",
    price: 200,
    vendorCode: 6,
    image: "108",
    categoryId: 1,
    subCategoryId: 9,
    isAvailable: false,
  },

  {
    id: 109,
    name: "Бегония Baladin",
    description: "",
    price: 200,
    vendorCode: 7,
    image: "109",
    categoryId: 1,
    subCategoryId: 9,
    isAvailable: false,
  },

  {
    id: 110,
    name: "Бегония Bela Lilac pink",
    description: "",
    price: 200,
    vendorCode: 8,
    image: "110",
    categoryId: 1,
    subCategoryId: 9,
    isAvailable: false,
  },
  {
    id: 111,
    name: "Бегония Элатиор Barkos",
    description: "",
    price: 200,
    vendorCode: 9,
    image: "111",
    categoryId: 1,
    subCategoryId: 9,
    isAvailable: false,
  },

  {
    id: 112,
    name: "Бегония элатиор Borias",
    description: "",
    price: 200,
    vendorCode: 10,
    image: "112",
    categoryId: 1,
    subCategoryId: 9,
    isAvailable: false,
  },

  {
    id: 113,
    name: "Бегония Rebecca",
    description: "",
    price: 200,
    vendorCode: 11,
    image: "113",
    categoryId: 1,
    subCategoryId: 9,
    isAvailable: false,
  },
];

const CAT_1_SUBCAT_2: CatalogItem[] = [
  {
    id: 43,
    name: "Вербена Empress Sun White",
    description:
      "Ампельная обильно цветущая ширина куста 40 - 60 см. Быстро разрастается, образует красивые ровные кустики из крупных чисто белого цвета соцветий. Подходит для посадки в подвесные, напольные кашпо и открытый грунт. Предпочитает солнечные места и обильный полив. Устойчива к непогоде.",
    price: 100,
    vendorCode: 12,
    image: "43",
    categoryId: 1,
    subCategoryId: 2,
    isAvailable: true,
  },
  {
    id: 44,
    name: "Вербена Empress Flair Pink Charme",
    description:
      "Ампельная обильно цветущая ширина куста 40 - 60 см. Быстро разрастается, образует красивые ровные кустики из крупных чисто белого цвета соцветий. Подходит для посадки в подвесные, напольные кашпо и открытый грунт. Предпочитает солнечные места и обильный полив. Устойчива к непогоде.",
    price: 100,
    vendorCode: 8,
    image: "44",
    categoryId: 1,
    subCategoryId: 2,
    isAvailable: true,
  },
  {
    id: 45,
    name: "Вербена Empress Sun Purple Charme",
    description:
      "Ампельная обильно цветущая ширина куста 40 - 60 см. Быстро разрастается, образует красивые ровные кустики из крупных чисто белого цвета соцветий. Подходит для посадки в подвесные, напольные кашпо и открытый грунт. Предпочитает солнечные места и обильный полив. Устойчива к непогоде.",
    price: 100,
    vendorCode: 14,
    image: "45",
    categoryId: 1,
    subCategoryId: 2,
    isAvailable: true,
  },
  {
    id: 46,
    name: "Вербена Empress Sun Red",
    description:
      "Ампельная обильно цветущая ширина куста 40 - 60 см. Быстро разрастается, образует красивые ровные кустики из крупных чисто белого цвета соцветий. Подходит для посадки в подвесные, напольные кашпо и открытый грунт. Предпочитает солнечные места и обильный полив. Устойчива к непогоде.",
    price: 100,
    vendorCode: 604,
    image: "46",
    categoryId: 1,
    subCategoryId: 2,
    isAvailable: true,
  },
  {
    id: 47,
    name: "Вербена Empress Flair Violet Blue",
    description:
      "Ампельная обильно цветущая ширина куста 40 - 60 см. Быстро разрастается, образует красивые ровные кустики из крупных чисто белого цвета соцветий. Подходит для посадки в подвесные, напольные кашпо и открытый грунт. Предпочитает солнечные места и обильный полив. Устойчива к непогоде.",
    price: 100,
    vendorCode: 608,
    image: "47",
    categoryId: 1,
    subCategoryId: 2,
    isAvailable: true,
  },
  {
    id: 48,
    name: "Вербена Samira Deep Red Star",
    description:
      "Ампельная обильно цветущая ширина куста 40 - 60 см. Быстро разрастается, образует красивые ровные кустики из крупных чисто белого цвета соцветий. Подходит для посадки в подвесные, напольные кашпо и открытый грунт. Предпочитает солнечные места и обильный полив. Устойчива к непогоде.",
    price: 100,
    vendorCode: 7,
    image: "48",
    categoryId: 1,
    subCategoryId: 2,
    isAvailable: true,
  },
  {
    id: 49,
    name: "Вербена Drums Purple Red",
    description:
      "Ампельная обильно цветущая ширина куста 40 - 60 см. Быстро разрастается, образует красивые ровные кустики из крупных чисто белого цвета соцветий. Подходит для посадки в подвесные, напольные кашпо и открытый грунт. Предпочитает солнечные места и обильный полив. Устойчива к непогоде.",
    price: 100,
    vendorCode: 15,
    image: "49",
    categoryId: 1,
    subCategoryId: 2,
    isAvailable: true,
  },
  {
    id: 50,
    name: "Вербена Lanai Twister Blue",
    description:
      "Ампельная обильно цветущая ширина куста 40 - 60 см. Быстро разрастается, образует красивые ровные кустики из крупных чисто белого цвета соцветий. Подходит для посадки в подвесные, напольные кашпо и открытый грунт. Предпочитает солнечные места и обильный полив. Устойчива к непогоде.",
    price: 100,
    vendorCode: 16,
    image: "50",
    categoryId: 1,
    subCategoryId: 2,
    isAvailable: true,
  },
  {
    id: 51,
    name: "Вербена Vanessa Compact Lime",
    description:
      "Ампельная обильно цветущая ширина куста 40 - 60 см. Быстро разрастается, образует красивые ровные кустики из крупных чисто белого цвета соцветий. Подходит для посадки в подвесные, напольные кашпо и открытый грунт. Предпочитает солнечные места и обильный полив. Устойчива к непогоде.",
    price: 100,
    vendorCode: 17,
    image: "51",
    categoryId: 1,
    subCategoryId: 2,
    isAvailable: true,
  },
  {
    id: 138,
    name: "Вербена Drums Dark Purple",
    description:
      "Ампельная обильно цветущая ширина куста 40 - 60 см. Быстро разрастается, образует красивые ровные кустики из крупных чисто белого цвета соцветий. Подходит для посадки в подвесные, напольные кашпо и открытый грунт. Предпочитает солнечные места и обильный полив. Устойчива к непогоде.",
    price: 100,
    vendorCode: 10,
    image: "138",
    categoryId: 1,
    subCategoryId: 2,
    isAvailable: true,
  },
];

const CAT_1_SUBCAT_4: CatalogItem[] = [
  {
    id: 52,
    name: "Sunny Compact Hazel",
    description:
      "Компактная крупноцветковая серия. Высоту достигает 20см. Цветет на протяжении всего сезона до самых заморозков. Куст очень плотный и жесткий.",
    price: 100,
    vendorCode: 6,
    image: "52",
    categoryId: 1,
    subCategoryId: 4,
    isAvailable: true,
  },
  {
    id: 53,
    name: "Sunny FELIX",
    description:
      " Компактная крупноцветковая серия. Высоту достигает 20см. Цветет на протяжении всего сезона до самых заморозков. Куст очень плотный и жесткий.",
    price: 100,
    vendorCode: 7,
    image: "53",
    categoryId: 1,
    subCategoryId: 4,
    isAvailable: true,
  },
  {
    id: 54,
    name: "Sunny Gaia",
    description:
      "Компактная крупноцветковая серия. Высоту достигает 20см. Цветет на протяжении всего сезона до самых заморозков. Куст очень плотный и жесткий.",
    price: 100,
    vendorCode: 8,
    image: "54",
    categoryId: 1,
    subCategoryId: 4,
    isAvailable: true,
  },
  {
    id: 55,
    name: "Blueberry Shake",
    description:
      "Кусты прямостоячие, ветвистые. Цветки до 6 см в диаметре. Цветет на протяжении всего сезона до самых заморозков. Высота 25 – 35 см, ширина 35 – 50 см.",
    price: 100,
    vendorCode: 1,
    image: "55",
    categoryId: 1,
    subCategoryId: 4,
    isAvailable: true,
  },
  {
    id: 56,
    name: "Lemon Ice",
    description:
      "Кусты прямостоячие, ветвистые. Цветки до 6 см в диаметре. Цветет на протяжении всего сезона до самых заморозков. Высота 25 – 35 см, ширина 35 – 50 см.",
    price: 100,
    vendorCode: 2,
    image: "56",
    categoryId: 1,
    subCategoryId: 4,
    isAvailable: true,
  },
  {
    id: 57,
    name: "Violet Ice",
    description:
      "Кусты прямостоячие, ветвистые. Цветки до 6 см в диаметре. Цветет на протяжении всего сезона до самых заморозков. Высота 25 – 35 см, ширина 35 – 50 см.",
    price: 100,
    vendorCode: 3,
    image: "57",
    categoryId: 1,
    subCategoryId: 4,
    isAvailable: true,
  },
  {
    id: 58,
    name: "Dalina Double Francisco",
    description:
      "Крупноцветковый остеоспермум. Низкорослый. Высота куста до 40 см. Очень обильно цветущий. Засухоустойчив. Цветы махрового типа.",
    price: 100,
    vendorCode: 4,
    image: "58",
    categoryId: 1,
    subCategoryId: 4,
    isAvailable: true,
  },
  {
    id: 59,
    name: "Margarita Yellow",
    description:
      "Кусты прямостоячие, ветвистые. Цветки до 6 см в диаметре. Цветет на протяжении всего сезона до самых заморозков. Высота 25 – 35 см, ширина 35 – 50 см.",
    price: 100,
    vendorCode: 5,
    image: "59",
    categoryId: 1,
    subCategoryId: 4,
    isAvailable: true,
  },
  {
    id: 60,
    name: "Flower Power Tropic Sun",
    description:
      "Кусты прямостоячие, ветвистые. Цветки до 6 см в диаметре. Цветет на протяжении всего сезона до самых заморозков. Высота 25 – 35 см, ширина 35 – 50 см.",
    price: 100,
    vendorCode: 9,
    image: "60",
    categoryId: 1,
    subCategoryId: 4,
    isAvailable: true,
  },

  {
    id: 61,
    name: "Margarita Double White",
    description:
      "Кусты прямостоячие, ветвистые. Цветки до 6 см в диаметре. Цветет на протяжении всего сезона до самых заморозков. Высота 25 – 35 см, ширина 35 – 50 см.",
    price: 100,
    vendorCode: 10,
    image: "61",
    categoryId: 1,
    subCategoryId: 4,
    isAvailable: true,
  },
  {
    id: 62,
    name: "Махровый 3D Deep Sun",
    description:
      "Кусты прямостоячие, ветвистые. Цветки до 6 см в диаметре. Цветет на протяжении всего сезона до самых заморозков. Высота 25 – 35 см, ширина 35 – 50 см.",
    price: 100,
    vendorCode: 11,
    image: "62",
    categoryId: 1,
    subCategoryId: 4,
    isAvailable: true,
  },
  {
    id: 63,
    name: "Margarita Double Pink",
    description:
      "Кусты прямостоячие, ветвистые. Цветки до 6 см в диаметре. Цветет на протяжении всего сезона до самых заморозков. Высота 25 – 35 см, ширина 35 – 50 см.",
    price: 100,
    vendorCode: 12,
    image: "63",
    categoryId: 1,
    subCategoryId: 4,
    isAvailable: true,
  },
];

const CAT_1_SUBCAT_1: CatalogItem[] = [
  {
    id: 1,
    name: "Петуния Ray Pistachio Cream",
    description:
      "Изящная петуния с красивой шарообразной формой и компактным габитусом. Новый оригинальный сорт высота 20-25 см. крупные цветки. Раннее, продолжительное и обильное цветение. Великолепно смотрится в кашпо. Подходит для небольших горшков.",
    price: 130,
    vendorCode: 1,
    image: "1",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 2,
    name: "Петуния Cascadias Fantasy Hot Pink",
    description:
      "Одна из самых популярных серий каскадной петунии, благодаря отличному ветвлению образует пышный шар диаметром до 80 см. Идеально подходит для подвесных кашпо, вазонов и балконных ящиков.",
    price: 130,
    vendorCode: 39,
    image: "2",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 3,
    name: "Петуния Cascadias Iceberg",
    description:
      "Одна из самых популярных серий каскадной петунии, благодаря отличному ветвлению образует пышный шар диаметром до 80 см. Идеально подходит для подвесных кашпо, вазонов и балконных ящиков.",
    price: 130,
    vendorCode: 36,
    image: "3",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 4,
    name: "Петуния Cascadias Rim Chianti",
    description:
      "Одна из самых популярных серий каскадной петунии, благодаря отличному ветвлению образует пышный шар диаметром до 80 см. Идеально подходит для подвесных кашпо, вазонов и балконных ящиков.",
    price: 130,
    vendorCode: 4,
    image: "4",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 5,
    name: "Петуния Potunia Purple",
    description:
      "Популярная серия гибридной петунии с полуампельным габитусом и оригинальными окрасками цветков, высота 20-30 см, побеги 60-70 см. Шикарные шарообразные шапки слегка приподнимаются над кашпо.",
    price: 130,
    vendorCode: 5,
    image: "5",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 6,
    name: "Петуния Potunia White",
    description:
      "Популярная серия гибридной петунии с полуампельным габитусом и оригинальными окрасками цветков, высота 20-30 см, побеги 60-70 см. Шикарные шарообразные шапки слегка приподнимаются над кашпо.",
    price: 130,
    vendorCode: 7,
    image: "6",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 7,
    name: "Петуния Cascadias Pitaya",
    description:
      "Одна из самых популярных серий каскадной петунии, благодаря отличному ветвлению образует пышный шар диаметром до 80 см. Идеально подходит для подвесных кашпо, вазонов и балконных ящиков.",
    price: 130,
    vendorCode: 385,
    image: "7",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 8,
    name: "Петуния Blanket Rose",
    description:
      "Cуперкаскадная петуния с некрупными цветками. Один из самых мощных ампелей. В диаметре может достигать более двух метров. Куст идеальный, не требует формирования. Цветы мелкие, в форме колокольчиков, где-то 3 см, но цветение суперобильное на протяжении всего сезона. Эта петуния покрывает пространство вокруг, словно плотным одеялом.",
    price: 130,
    vendorCode: 8,
    image: "8",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 9,
    name: "Петуния Blanket White",
    description:
      "Cуперкаскадная петуния с некрупными цветками. Один из самых мощных ампелей. В диаметре может достигать более двух метров. Куст идеальный, не требует формирования. Цветы мелкие, в форме колокольчиков, где-то 3 см, но цветение суперобильное на протяжении всего сезона. Эта петуния покрывает пространство вокруг, словно плотным одеялом.",
    price: 130,
    vendorCode: 9,
    image: "9",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 11,
    name: "Петхоа Beautical Caramel Yellow",
    description:
      "Гибрид петунии и калибрахоа. От Калибрахоа эта сортосерия взяла яркие цвета, от петунии- выносливость. Cорт компактный, цветы среднего размера. Отлично держит непогоду, выдерживает палящее солнце, плети не страдают от ветра, быстро восстанавливается после дождя.",
    price: 130,
    vendorCode: 390,
    image: "11",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 10,
    name: "Петуния Mystical Midnight Gold",
    description:
      "Это мощное, чрезвычайно ветвистое растение. Изобилие его великолепных цветов замечательно выглядит каскадом из подвесных корзин или контейнеров.",
    price: 130,
    vendorCode: 402,
    image: "10",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 12,
    name: "Петуния Glacier Sky",
    description:
      "Идеальная ампельная петуния для подвесных корзин. Длина побегов 60-80 см., энергичный рост и великолепная устойчивость к неблагоприятной погоде.",
    price: 130,
    vendorCode: 349,
    image: "12",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },

  {
    id: 13,
    name: "Петуния Crazytunia Moonstruck",
    description:
      "Cерия петуний с уникальными и редкими окрасками цветков имеет средний рост в отличии от традиционных ампельных петуний, очень пышные плотные шапки, усыпанные множеством цветков, высокая устойчивость к непогоде.",
    price: 130,
    vendorCode: 309,
    image: "13",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 14,
    name: "Петуния Splash Dance Magenta Mambo",
    description:
      "Яркий и красивый сорт, очень обильно цветущее компактное растение, отличается крупными цветками диаметром до 10 см. ",
    price: 130,
    vendorCode: 206,
    image: "14",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 15,
    name: "Петуния Sweetunia Black Satin",
    description:
      "Популярная серия гибридной петунии с полуампельным габитусом и оригинальными окрасками цветков, высота 20-30 см, побеги 60-70 см. Шикарные шарообразные шапки слегка приподнимаются над кашпо.",
    price: 130,
    vendorCode: 117,
    image: "15",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 16,
    name: "Петуния Surfinia Table White",
    description:
      "Компактная плотная форма. Гибкие ветки образуют настоящий водопад, особенно эффектный в подвесных корзинах",
    price: 130,
    vendorCode: 62,
    image: "16",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 17,
    name: "Петуния Amore Fiesta",
    description:
      "Великолепная шарообразная полуампельная форма, отличное ветвление, не оголяется в центре. Очень пышное и раннее цветение, устойчивость к непогоде.",
    price: 130,
    vendorCode: 141,
    image: "17",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 18,
    name: "Петуния Amore Queen of Hearts",
    description:
      "Великолепная шарообразная полуампельная форма, отличное ветвление, не оголяется в центре. Очень пышное и раннее цветение, устойчивость к непогоде.",
    price: 130,
    vendorCode: 144,
    image: "18",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 19,
    name: "Петуния Cascadias Rim Magenta",
    description:
      "Одна из самых популярных серий каскадной петунии, благодаря отличному ветвлению образует пышный шар диаметром до 80 см. Идеально подходит для подвесных кашпо, вазонов и балконных ящиков.",
    price: 130,
    vendorCode: 31,
    image: "19",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 20,
    name: "Петуния Cascadias Rim Violet",
    description:
      "Одна из самых популярных серий каскадной петунии, благодаря отличному ветвлению образует пышный шар диаметром до 80 см. Идеально подходит для подвесных кашпо, вазонов и балконных ящиков.",
    price: 130,
    vendorCode: 43,
    image: "20",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 21,
    name: "Петуния Splash Dance Violet Vogue",
    description:
      " Формирует огромные густые кусты с плотным цветением. Ширина до 60 см ",
    price: 130,
    vendorCode: 203,
    image: "21",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 22,
    name: "Петуния Bonnie Mystery Sky",
    description:
      "Петуния с полуампельной формой и ранним цветением. Cредний рост и прекрасная аккуратная форма, очень продолжительное обильное цветение.",
    price: 130,
    vendorCode: 6,
    image: "22",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 23,
    name: "Петуния Littletunia Blue Vein",
    description:
      "Отличная серия ампельных петуний с мелкими цветками и компактной формой. Образует плотный шар высотой 30-40 см., цветки 2-3 см ",
    price: 130,
    vendorCode: 2,
    image: "23",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 24,
    name: "Petunia Peppy Blueberry Muffin",
    description:
      "Ампельная петуния, все сорта имеют цветы со звездой. Высота куста 20 см, длина побегов 45-50 см. Крупные цветки, обильное и продолжительное цветение. Образует шикарные шапки благодаря отличному ветвлению, форма куста каскадная, нарастает быстро.",
    price: 130,
    vendorCode: 11,
    image: "24",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 25,
    name: "Петуния Surprise Kardinal",
    description:
      "Каскадная петуния, образующая очень пышные, шарообразные шапки. Высота 40-50 см., плотное, обильное цветение",
    price: 130,
    vendorCode: 444,
    image: "25",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 26,
    name: "Петуния Sweetunia Johnny Flame",
    description:
      "Популярная серия петунии с полуампельным габитусом и оригинальными окрасками цветков. Высота 20-30 см, побеги 60-70 см, обильное и продолжительное цветение.",
    price: 130,
    vendorCode: 12,
    image: "26",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 27,
    name: "Петуния Sweetunia Purple Gem",
    description:
      "Популярная серия петунии с полуампельным габитусом и оригинальными окрасками цветков. Высота 20-30 см, побеги 60-70 см, обильное и продолжительное цветение.",
    price: 130,
    vendorCode: 13,
    image: "27",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 28,
    name: "Петуния Sweetunia Purple Touch",
    description:
      "Популярная серия петунии с полуампельным габитусом и оригинальными окрасками цветков. Высота 20-30 см, побеги 60-70 см, обильное и продолжительное цветение.",
    price: 130,
    vendorCode: 14,
    image: "28",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 29,
    name: "Петуния Sweetunia Suzie Storm",
    description:
      "Популярная серия петунии с полуампельным габитусом и оригинальными окрасками цветков. Высота 20-30 см, побеги 60-70 см, обильное и продолжительное цветение.",
    price: 130,
    vendorCode: 15,
    image: "29",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 30,
    name: "Петуния Sweetunia Starfish",
    description:
      "Популярная серия петунии с полуампельным габитусом и оригинальными окрасками цветков. Высота 20-30 см, побеги 60-70 см, обильное и продолжительное цветение.",
    price: 130,
    vendorCode: 16,
    image: "30",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 31,
    name: "Петуния Potunia Piccola Magenta Star",
    description:
      "Кусты компактные, пышные, хорошо сохраняют шаровидную форму и ветвятся. Боковые побеги формируются без дополнительных прищипок. Cорта устойчивы к перепадам температуры, болезням, дождю. Высота куста до 50см.",
    price: 130,
    vendorCode: 17,
    image: "31",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 32,
    name: "Петуния Potunia Pinkalicious",
    description:
      "Популярная серия петунии с полуампельным габитусом и оригинальными окрасками цветков. Высота 20-30 см, побеги 60-70 см, обильное и продолжительное цветение.",
    price: 130,
    vendorCode: 18,
    image: "32",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 33,
    name: "Петуния Surprise Red",
    description:
      "Каскадная петуния, образующая очень пышные, шарообразные шапки. Высота 40-50 см., плотное, обильное цветение",
    price: 130,
    vendorCode: 446,
    image: "33",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 34,
    name: "Петуния Surprise Sparkling Cardinal",
    description:
      "Каскадная петуния, образующая очень пышные, шарообразные шапки. Высота 40-50 см., плотное, обильное цветение",
    price: 130,
    vendorCode: 20,
    image: "34",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 35,
    name: "Петуния Surprise Sparkling Purple ",
    description:
      "Каскадная петуния, образующая очень пышные, шарообразные шапки. Высота 40-50 см., плотное, обильное цветение",
    price: 130,
    vendorCode: 21,
    image: "35",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 36,
    name: "Петуния Surprise Sparkling Blue",
    description:
      "Каскадная петуния, образующая очень пышные, шарообразные шапки. Высота 40-50 см., плотное, обильное цветение",
    price: 130,
    vendorCode: 216,
    image: "36",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 37,
    name: "Петуния Potunia Canary Yellow",
    description:
      "Каскадная петуния, образующая очень пышные, шарообразные шапки. Высота 40-50 см., плотное, обильное цветение",
    price: 130,
    vendorCode: 22,
    image: "37",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 38,
    name: "Петуния Potunia Piccola Cobalt Blue",
    description:
      "Каскадная петуния, образующая очень пышные, шарообразные шапки. Высота 40-50 см., плотное, обильное цветение",
    price: 130,
    vendorCode: 23,
    image: "38",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 39,
    name: "Peppy Hot Red 2024",
    description:
      "Ампельная петуния, все сорта имеют цветы со звездой. Высота куста 20 см, длина побегов 45-50 см. Крупные цветки, обильное и продолжительное цветение. Образует шикарные шапки благодаря отличному ветвлению, форма куста каскадная, нарастает быстро.",
    price: 130,
    vendorCode: 24,
    image: "39",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  {
    id: 40,
    name: "Peppy Bee (Smartunia Windmill) (Intrinsa)",
    description:
      "Ампельная петуния, все сорта имеют цветы со звездой. Высота куста 20 см, длина побегов 45-50 см. Крупные цветки, обильное и продолжительное цветение. Образует шикарные шапки благодаря отличному ветвлению, форма куста каскадная, нарастает быстро.",
    price: 130,
    vendorCode: 25,
    image: "40",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 41,
    name: "Петуния Surprise Sparkling Red",
    description:
      "Каскадная петуния, образующая очень пышные, шарообразные шапки. Высота 40-50 см., плотное, обильное цветение",
    price: 130,
    vendorCode: 212,
    image: "41",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 42,
    name: "Петуния Peppy Blue 2024",
    description:
      "Ампельная петуния, все сорта имеют цветы со звездой. Высота куста 20 см, длина побегов 45-50 см. Крупные цветки, обильное и продолжительное цветение. Образует шикарные шапки благодаря отличному ветвлению, форма куста каскадная, нарастает быстро.",
    price: 130,
    vendorCode: 26,
    image: "42",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },
  //
  {
    id: 114,
    name: "Tumbelina Bella",
    description: "",
    price: 130,
    vendorCode: 37,
    image: "114",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 115,
    name: "Tumbelina Belinda",
    description: "",
    price: 130,
    vendorCode: 35,
    image: "115",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 116,
    name: "Tumbelina Compact Nicola",
    description: "",
    price: 130,
    vendorCode: 33,
    image: "116",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },

  {
    id: 117,
    name: "Tumbelina Compact Scarlet Ripple",
    description: "",
    price: 130,
    vendorCode: 32,
    image: "117",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },

  {
    id: 118,
    name: "Tumbelina Darcey Rosa",
    description: "",
    price: 130,
    vendorCode: 42,
    image: "118",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 119,
    name: "Tumbelina Helena",
    description: "",
    price: 130,
    vendorCode: 44,
    image: "119",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },

  {
    id: 120,
    name: "Tumbelina Savanna",
    description: "",
    price: 130,
    vendorCode: 40,
    image: "120",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },

  {
    id: 121,
    name: "Tumbelina Sophia",
    description: "",
    price: 130,
    vendorCode: 45,
    image: "121",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 122,
    name: "Tumbelina Superstar",
    description: "",
    price: 130,
    vendorCode: 41,
    image: "122",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },

  {
    id: 123,
    name: "Tumbelina Matilda",
    description: "",
    price: 130,
    vendorCode: 46,
    image: "123",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 124,
    name: "Potunia Blueberry Ice",
    description: "",
    price: 130,
    vendorCode: 47,
    image: "124",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 125,
    name: "Potunia Coral",
    description: "",
    price: 130,
    vendorCode: 48,
    image: "125",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  //
  {
    id: 127,
    name: "Петхоа Beautical Sunset Orange",
    description: "",
    price: 130,
    vendorCode: 49,
    image: "127",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 128,
    name: "Петхоа BeautiCal Yellow Sun",
    description: "",
    price: 130,
    vendorCode: 50,
    image: "128",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 129,
    name: "Петхоа Beautical Pearl White",
    description: "",
    price: 130,
    vendorCode: 51,
    image: "129",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },

  {
    id: 130,
    name: "Петхоа Beautical Red Maple",
    description: "",
    price: 130,
    vendorCode: 52,
    image: "130",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },

  {
    id: 131,
    name: "Петхоа Cascadias Rim Cherry",
    description: "",
    price: 130,
    vendorCode: 369,
    image: "131",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 132,
    name: "Cascadias Bicolor Cabernet",
    description: "",
    price: 130,
    vendorCode: 30,
    image: "132",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },

  {
    id: 133,
    name: "Петуния Cascadias Arizona Sky",
    description: "",
    price: 130,
    vendorCode: 53,
    image: "133",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: false,
  },

  {
    id: 134,
    name: "Littletunia Bright Red",
    description: "",
    price: 130,
    vendorCode: 54,
    image: "134",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 135,
    name: "Littletunia Pink Splash",
    description: "",
    price: 130,
    vendorCode: 55,
    image: "135",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },

  {
    id: 136,
    name: "Littletunia White Grace",
    description: "",
    price: 130,
    vendorCode: 56,
    image: "136",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 137,
    name: "Петуния Night Sky",
    description: "",
    price: 130,
    vendorCode: 57,
    image: "137",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 150,
    name: "Петуния Origami White",
    description: "",
    price: 130,
    vendorCode: 60,
    image: "150",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 151,
    name: "Петуния Origami Marine",
    description: "",
    price: 130,
    vendorCode: 61,
    image: "151",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 152,
    name: "Петуния Origami Lavender Touch",
    description: "",
    price: 130,
    vendorCode: 63,
    image: "152",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
  {
    id: 153,
    name: "Петуния Peppy Yellow Red",
    description: "",
    price: 130,
    vendorCode: 64,
    image: "153",
    categoryId: 1,
    subCategoryId: 1,
    isAvailable: true,
  },
];

export const ITEMS_LIST: CatalogItem[] = (() => {
  const sortedList = [
    ...CAT_1_SUBCAT_1,
    ...CAT_1_SUBCAT_2,
    ...CAT_1_SUBCAT_4,
    ...CAT_1_SUBCAT_7,
    ...CAT_1_SUBCAT_8,
    ...CAT_1_SUBCAT_9,
  ].sort((a, b) => a.name.localeCompare(b.name));

  const notAvailableList: CatalogItem[] = [];

  return sortedList
    .reduce<CatalogItem[]>((acc, item) => {
      if (item.isAvailable) {
        acc.push(item);
        return acc;
      }

      notAvailableList.push(item);
      return acc;
    }, [])
    .concat(notAvailableList);
})();

export const SUB_CATEGORIES_MAP: Record<
  CategoryItem["id"],
  Record<CategoryItem["id"], CategoryItem>
> = {
  1: {
    1: {
      id: 1,
      value: "Петуния",
      subItems: null,
      length: CAT_1_SUBCAT_1.length,
    },
    2: {
      id: 2,
      value: "Вербена",
      subItems: null,
      length: CAT_1_SUBCAT_2.length,
    },
    3: {
      id: 3,
      value: "Калибрахоа",
      subItems: null,
    },
    4: {
      id: 4,
      value: "Остеоспермум",
      subItems: null,
      length: CAT_1_SUBCAT_4.length,
    },
    5: {
      id: 5,
      value: "Пеларгония",
      subItems: null,
    },
    7: {
      id: 7,
      value: "Фуксия",
      subItems: null,
      length: CAT_1_SUBCAT_7.length,
    },
    8: {
      id: 8,
      value: "Георгины",
      subItems: null,
      length: CAT_1_SUBCAT_8.length,
    },
    9: {
      id: 9,
      value: "Бегония",
      subItems: null,
      length: CAT_1_SUBCAT_9.length,
    },
  },
};

export const CATEGORIES_MAP: Record<CategoryItem["id"], CategoryItem> = {
  1: {
    id: 1,
    value: "Укоренённые черенки",
    subItems: Object.values(SUB_CATEGORIES_MAP[1]),
  },
  2: {
    id: 2,
    value: "Другое",
    subItems: null,
  },
};

export const CATEGORIES_LIST = Object.values(CATEGORIES_MAP);
